serviceaccount: webhook-injector
deploymentName: webhook-server
webhookName: webhook-nd

replicas: 1
certValidityDays: 1024

timeoutSeconds: 2
failurePolicy: Ignore
useServiceCAonOCP: true

webhook:
  logLevel: INFO

# service type and port for webhook server
service:
  type: ClusterIP
  port: 443

# image for pods running the webhook functionality
image:
  repository: cavissonsystem/nd_webhook_injector  
  tag: 4.15.0.B123
  pullPolicy: Always

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

NDController:
  proxyip: cavproxy.cavisson.svc.cluster.local                 #<service-name>.<namespace>.svc.cluster.local
  proxyport: 443
  proxymode: 1

instrumentationTemplates:
   - name: nodejs-default
    injectionRules:
      technology: nodejs
      image: cavissonsystem/nodejs-agent:4.15.0.B132  # TODO: replace with cavissonsystem nodejs agent image
      TierNameSource: auto

      env:
        - name: CAV_APP_AGENT_AGENTLOGGINGMODE
          value: "ALL"
        - name: CAV_APP_AGENT_NDCHOST
          value: "netcloud4-15-u24.cav-test.com"
        - name: CAV_APP_AGENT_NDCPORT
          value: "4433"
        - name: CAV_APP_AGENT_NDC_COMM_PROTOCOL
          value: "WSS"


instrumentationRules:
  
  - name: cav-nodejs-agent
    matchRules:
      namespaceRegex: .*
      # - com.cavisson/inject-nodejs: "true"
      podNameRegex: ^(video|directv|dtv|sst|digital|fr)
    injectionRules:
      template: nodejs-default
      containerMatch:
        excludeContainerNames:
          - istio-proxy
